apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jeoy6fs01-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:3cbc35ce3f4f9a45aa34536f602a83e0bedf551b@sha256:fa96cd99480f818070b16f5bb3018c4d5fa1f6e3a1ac7ee7433e8a53a37ed5cd
          name: container-image
